# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


# NOTE: This is not the way a Kafka cluster would normally be deployed in production, as it is not secure
# and is not fault tolerant. This example is a toy deployment that is only meant to exercise the Kafka code path
# of the ordering service.

version: '2'

networks:
  byfn:

services:

  zookeeper1.vodworks.com:
    container_name: zookeeper1.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - byfn
    
  zookeeper2.vodworks.com:
    container_name: zookeeper2.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
    networks:
      - byfn

  zookeeper3.vodworks.com:
    container_name: zookeeper3.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888
    networks:
      - byfn

  kafka1.vodworks.com:
    container_name: kafka1.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    depends_on:
      - zookeeper1.vodworks.com
      - zookeeper2.vodworks.com
      - zookeeper3.vodworks.com
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1.vodworks.com:9092
    networks:
      - byfn
  
  kafka2.vodworks.com:
    container_name: kafka2.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    depends_on:
      - zookeeper1.vodworks.com
      - zookeeper2.vodworks.com
      - zookeeper3.vodworks.com
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2.vodworks.com:9092
    networks:
      - byfn

  kafka3.vodworks.com:
    container_name: kafka3.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    depends_on:
      - zookeeper1.vodworks.com
      - zookeeper2.vodworks.com
      - zookeeper3.vodworks.com
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3.vodworks.com:9092
    networks:
      - byfn

  kafka4.vodworks.com:
    container_name: kafka4.vodworks.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    depends_on:
      - zookeeper1.vodworks.com
      - zookeeper2.vodworks.com
      - zookeeper3.vodworks.com
    environment:
      - KAFKA_BROKER_ID=4
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka4.vodworks.com:9092
    networks:
      - byfn