# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer0.vodworks.com:
  orderer1.vodworks.com:
  peer0.telco1.vodworks.com:
  peer1.telco1.vodworks.com:
  peer0.telco2.vodworks.com:
  peer1.telco2.vodworks.com:

networks:
  byfn:

services:
  
  ca.telco1.vodworks.com:
    extends:
      file:   docker-compose-e2e.yaml
      service: ca0
    container_name: ca.telco1.vodworks.com
    networks:
      - byfn

  ca.telco2.vodworks.com:
    extends:
      file:   docker-compose-e2e.yaml
      service: ca1
    container_name: ca.telco2.vodworks.com
    networks:
      - byfn

  orderer0.vodworks.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.vodworks.com
    container_name: orderer0.vodworks.com
    networks:
      - byfn

  orderer1.vodworks.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.vodworks.com
    container_name: orderer1.vodworks.com
    networks:
      - byfn

  peer0.telco1.vodworks.com:
    container_name: peer0.telco1.vodworks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.telco1.vodworks.com
    networks:
      - byfn

  peer1.telco1.vodworks.com:
    container_name: peer1.telco1.vodworks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.telco1.vodworks.com
    networks:
      - byfn

  peer0.telco2.vodworks.com:
    container_name: peer0.telco2.vodworks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.telco2.vodworks.com
    networks:
      - byfn

  peer1.telco2.vodworks.com:
    container_name: peer1.telco2.vodworks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.telco2.vodworks.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.telco1.vodworks.com:7051
      - CORE_PEER_LOCALMSPID=Telco1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/telco1.vodworks.com/peers/peer0.telco1.vodworks.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/telco1.vodworks.com/peers/peer0.telco1.vodworks.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/telco1.vodworks.com/peers/peer0.telco1.vodworks.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/telco1.vodworks.com/users/Admin@telco1.vodworks.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer0.vodworks.com
      - orderer1.vodworks.com
      - ca.telco1.vodworks.com
      - ca.telco2.vodworks.com
      - peer0.telco1.vodworks.com
      - peer1.telco1.vodworks.com
      - peer0.telco2.vodworks.com
      - peer1.telco2.vodworks.com
    networks:
      - byfn
