NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.telco1.vodworks.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.telco1.vodworks.com-cert.pem
    OrganizationalUnitIdentifier: peer
