# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &Telco3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Telco3MSP

        # ID to load the MSP definition as
        ID: Telco3MSP

        MSPDir: crypto-config/peerOrganizations/telco3.vodworks.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Telco3MSP.admin', 'Telco3MSP.peer', 'Telco3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Telco3MSP.admin', 'Telco3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Telco3MSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.telco3.vodworks.com
              Port: 12051
